# Generated by Django 2.1.7 on 2019-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_delivery', '0002_emaildelivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
