# Generated by Django 2.1.7 on 2019-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_delivery', '0003_emaildelivery_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
